; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
board_build.filesystem = littlefs
build_src_filter = 
	+<*>
	-<ProgramFiles/RunProgram.cpp>
	-<ProgramFiles/StoppingTestProgram.cpp>
	-<ProgramFiles/RelayProgram.cpp>
	-<ProgramFiles/BatteryTestProgram.cpp>
	-<ProgramFiles/DemoProgram.cpp>
lib_deps = 
	adafruit/Adafruit AS7341@^1.4.1
	lorol/LittleFS_esp32@^1.0.6

#To Switch Mode use -D + [RUN_CAR, TEST_STOPPING, TEST_BATTERY, RELAY, DEMO]
build_flags = 
	-DTEST_STOPPING
